### ISSUE TITLE
制作datas出错

### ISSUE THREAD

**Issue by shbupt** [basketballandlearn/Dureader-Bert#1]
在第二步运行时报错：
Model name 'bert-base-chinese' was not found in model name list (bert-base-uncased, bert-large-uncased, bert-base-cased, bert-large-cased, bert-base-multilingual-uncased, bert-base-multilingual-cased, bert-base-chinese). We assumed 'https://s3.amazonaws.com/models.huggingface.co/bert/bert-base-chinese-vocab.txt' was a path or url but couldn't find any file associated to this path or url.
AttributeError: 'NoneType' object has no attribute 'convert_tokens_to_ids'

**Comment by shbupt** [comment]
> 在第二步运行时报错：
> Model name 'bert-base-chinese' was not found in model name list (bert-base-uncased, bert-large-uncased, bert-base-cased, bert-large-cased, bert-base-multilingual-uncased, bert-base-multilingual-cased, bert-base-chinese). We assumed 'https://s3.amazonaws.com/models.huggingface.co/bert/bert-base-chinese-vocab.txt' was a path or url but couldn't find any file associated to this path or url.
> AttributeError: 'NoneType' object has no attribute 'convert_tokens_to_ids'

**Comment by IrvingBei** [comment]
请问你是怎么解决的呀，我也遇到了这个问题，但是我修改后还是出错，谢谢啦
