### ISSUE TITLE
请教一下，predicting.py里头 prior_scores是怎么来的？

### ISSUE THREAD

**Issue by QixinLi** [basketballandlearn/Dureader-Bert#14]
`prior_scores=(0.44, 0.23, 0.15, 0.09, 0.07)`
是自己写的，还是有什么依据或者说法？

**Comment by basketballandlearn** [comment]
根据训练集答案出现在哪个文档的数量统计出来的

**Comment by QixinLi** [comment]
> 根据训练集答案出现在哪个文档的数量统计出来的

噢噢，懂了，感谢
