### ISSUE TITLE
python3环境下有问题

### ISSUE THREAD

**Issue by 1148270327** [basketballandlearn/Dureader-Bert#2]
感谢楼主的code和分享。执行sh run.sh --para_extraction报错，这个因为官方是用的python2.7。用py3报错信息为： __init__() got an unexpected keyword argument 'encoding'
，把json.dumps()改成python3版本后，解决这个错误了。
但依然不能执行，这个代码if p_idx < para_id:报错：提示int不能和None做比较。

**Comment by 1148270327** [comment]
cat $SOURCE_DIR/testset/search.test1.json | python paragraph_extraction.py test \
            > $TARGET_DIR/testset/search.test1.json
把官方数据拷过去后，这个test1是不是该改一下成test.json?

**Comment by basketballandlearn** [comment]
按照数据集实际名字来

**Comment by Jingyilang** [comment]
> 感谢楼主的code和分享。执行sh run.sh --para_extraction报错，这个因为官方是用的python2.7。用py3报错信息为： **init**() got an unexpected keyword argument 'encoding'
> ，把json.dumps()改成python3版本后，解决这个错误了。
> 但依然不能执行，这个代码if p_idx < para_id:报错：提示int不能和None做比较。

请问这个问题您解决了吗，我也遇到了这个问题

**Comment by basketballandlearn** [comment]
你好！
    没有碰到这个问题。但是看起来很容易解决，你可以抛出异常




------------------ 原始邮件 ------------------
发件人: "zzuczy"<notifications@github.com>;
发送时间: 2019年8月7日(星期三) 下午3:26
收件人: "basketballandlearn/Dureader-Bert"<Dureader-Bert@noreply.github.com>;
抄送: "暂无"<1643230637@qq.com>;"State change"<state_change@noreply.github.com>;
主题: Re: [basketballandlearn/Dureader-Bert] python3环境下有问题 (#2)



 
感谢楼主的code和分享。执行sh run.sh --para_extraction报错，这个因为官方是用的python2.7。用py3报错信息为： init() got an unexpected keyword argument 'encoding'
 ，把json.dumps()改成python3版本后，解决这个错误了。
 但依然不能执行，这个代码if p_idx < para_id:报错：提示int不能和None做比较。
  
请问这个问题您解决了吗，我也遇到了这个问题

**Comment by kumiko-oreyome** [comment]
會出現這樣的問題和PYTHON版本無關 而是Dureader的test data是沒有most_rel_para這個欄位
