### ISSUE TITLE
*Help* 试了作者预训练的macbert模型在CMRC 2018开发集上的推理效果，结果有出入，有同学试过吗？

### ISSUE THREAD

**Issue by XiaoqingNLP** [basketballandlearn/Dureader-Bert#48]
Results: {'exact': 79.77632805219012, 'f1': 80.07492714389267, 'total': 3219, 'HasAns_exact': 79.77632805219012, 'HasAns_f1': 80.07492714389267, 'HasAns_total': 3219, 'best_exact': 79.77632805219012, 'best_exact_thresh': 0.0, 'best_f1': 80.07492714389267, 'best_f1_thresh': 0.0}

**Comment by HL0718** [comment]
我加载的luhua/chinese_pretrain_mrc_macbert_large这个模型脚本，然后对cmrc数据进行微调，执行sh train_bert.sh脚本，发现一直卡在加载模型权重这里，请问是有什么问题吗？
